import Testing
@testable import SwiftyAPI

@Test
func builtinGeneratorCatalogIncludesInitialPairings() throws {
    let generators = SwiftyAPIBuiltinGenerators.all

    #expect(generators.map(\.registryKey).sorted() == [
        "client.curl.curl examples.request and response examples.builtin",
        "client.c#.net httpclient client.httpclient + system.text.json.builtin",
        "client.python.python httpx client.httpx + pydantic.builtin",
        "client.swift.swift urlsession client.urlsession.builtin",
        "client.typescript.typescript axios client.axios.builtin",
        "server.c#.net asp.net core server.asp.net core minimal api.builtin",
        "server.python.python fastapi server.fastapi + pydantic.builtin",
        "server.swift.swift vapor server.vapor.builtin",
        "server.typescript.typescript node server.node.builtin"
    ].sorted())

    let registry = try SwiftyAPIBuiltinGenerators.registry()
    #expect(registry.allGenerators().count == 9)
}

@Test
func curlExampleGeneratorProducesDesignMethodExamples() throws {
    let document = try OpenAPIDocument(
        source: """
        openapi: 3.0.3
        info:
          title: Example API
          version: 1.0.0
        servers:
          - url: https://api.example.com
        paths:
          /pets:
            post:
              summary: Create pet
              requestBody:
                required: true
                content:
                  application/json:
                    schema:
                      type: object
                      properties:
                        name:
                          type: string
                        age:
                          type: integer
              responses:
                '200':
                  description: Created
                  content:
                    application/json:
                      schema:
                        type: object
                        properties:
                          id:
                            type: integer
                          name:
                            type: string
        """,
        format: .yaml
    )
    let operation = try #require(document.summary.operations.first)
    let result = try SwiftyAPICurlExampleGenerator().generateMethod(
        from: SwiftyAPIMethodGenerationContext(
            title: document.summary.title,
            version: document.summary.version,
            serverURL: document.summary.servers.first,
            operation: operation
        ),
        options: SwiftyAPIGeneratorOptions()
    )

    #expect(result.requestExample.contains("curl --location --request POST 'https://api.example.com/pets'"))
    #expect(result.requestExample.contains("--header 'Content-Type: application/json'"))
    #expect(result.requestExample.contains("\"name\": \"name\""))
    #expect(result.responseExample.contains("\"id\": 0"))
    #expect(result.responseExample.contains("\"name\": \"name\""))
}

@Test
func javaScriptCoreGeneratorRunsFullAndMethodGeneration() throws {
    let document = try OpenAPIDocument(source: OpenAPITemplates.minimalYAML, format: .yaml)
    let operation = try #require(document.summary.operations.first)
    let generator = SwiftyAPIJavaScriptCoreGenerator(
        manifest: SwiftyAPIJavaScriptGeneratorManifest(
            name: "JavaScript Axios Client",
            description: "Example plugin.",
            language: "JavaScript",
            variation: "axios",
            type: "client",
            author: "Example",
            entryPoint: "plugin.js",
            supportedOutputs: [.client, .support]
        ),
        source: """
        function generateFull(payloadJSON) {
            const payload = JSON.parse(payloadJSON);
            return JSON.stringify({
                files: [{
                    path: "Client.js",
                    kind: "client",
                    contents: "// " + payload.document.summary.title
                }],
                diagnostics: [{
                    severity: "info",
                    message: "Generated by JavaScriptCore."
                }]
            });
        }

        function generateMethod(payloadJSON) {
            const payload = JSON.parse(payloadJSON);
            const operation = payload.context.operation;
            return JSON.stringify({
                requestExample: operation.method.toUpperCase() + " " + operation.path,
                responseExample: "handle " + operation.id,
                diagnostics: []
            });
        }
        """
    )

    let full = try generator.generateFull(from: document, options: SwiftyAPIGeneratorOptions())
    #expect(full.files == [
        SwiftyAPIGeneratedFile(
            path: "Client.js",
            kind: .client,
            contents: "// Example API"
        )
    ])
    #expect(full.diagnostics.first?.message == "Generated by JavaScriptCore.")

    let method = try generator.generateMethod(
        from: SwiftyAPIMethodGenerationContext(
            title: document.summary.title,
            version: document.summary.version,
            operation: operation
        ),
        options: SwiftyAPIGeneratorOptions()
    )
    #expect(method.requestExample == "GET /pets")
    #expect(method.responseExample == "handle GET /pets")
}
