/*
 SwiftyAPI JavaScript generator plugin example
 =============================================

 This file is intentionally verbose and heavily commented. It is meant to be
 copied, edited, and used as learning material for runtime plugins.

 SwiftyAPI executes this source with Apple's JavaScriptCore framework. The
 bridge looks for two global functions:

   - generateFull(payloadJSON)
   - generateMethod(payloadJSON)

 Both functions receive a JSON string and may return either a JavaScript object
 or a JSON string. This example returns JSON strings because that keeps the
 bridge boundary explicit and easy to debug.

 The generated output is plain JavaScript that uses Axios. The plugin itself
 does not import Axios; it only writes files that expect Axios in the consumer's
 project.
*/

function generateFull(payloadJSON) {
  var payload = JSON.parse(payloadJSON);
  var document = payload.document;
  var summary = document.summary;
  var operations = summary.operations || [];
  var clientName = pascalCase(summary.title || "API") + "Client";

  var files = [
    {
      path: "generated/client.js",
      kind: "client",
      contents: renderClientFile(clientName, summary, operations)
    },
    {
      path: "generated/models.js",
      kind: "model",
      contents: renderModelsFile(operations)
    },
    {
      path: "generated/README.md",
      kind: "support",
      contents: renderReadme(summary, operations)
    }
  ];

  return JSON.stringify({
    files: files,
    diagnostics: [
      {
        severity: "info",
        message: "Generated JavaScript Axios client with " + operations.length + " operations."
      }
    ]
  });
}

function generateMethod(payloadJSON) {
  var payload = JSON.parse(payloadJSON);
  var context = payload.context;
  var operation = context.operation;
  var functionName = camelCase(operation.operationID || operation.summary || operation.id);
  var requestBody = operation.requestBody;
  var requestSchemaName = requestBody ? requestModelName(operation) : "body";
  var response = primaryResponse(operation);
  var responseSchemaName = response ? responseModelName(operation, response) : "response";

  var requestExample = [
    "async function " + functionName + "(http" + (requestBody ? ", " + requestSchemaName : "") + ") {",
    "  const response = await http." + operation.method + "(",
    "    " + JSON.stringify(operation.path) + (requestBody ? "," : ""),
    requestBody ? "    " + requestSchemaName + "," : "",
    "    { headers: { \"Accept\": \"application/json\" } }",
    "  );",
    "  return response.data;",
    "}",
    "",
    "// Example call",
    "const result = await " + functionName + "(axios.create({ baseURL: " + JSON.stringify(context.serverURL || "/") + " })" + (requestBody ? ", " + exampleObject(requestBody.schemaFields) : "") + ");"
  ].filter(Boolean).join("\n");

  var responseExample = [
    "// " + (response ? response.statusCode : "200") + " " + (response && response.description ? response.description : "Response"),
    "const " + responseSchemaName + " = " + exampleObject(response ? response.schemaFields : []) + ";"
  ].join("\n");

  return JSON.stringify({
    requestExample: requestExample,
    responseExample: responseExample,
    diagnostics: []
  });
}

function renderClientFile(clientName, summary, operations) {
  var lines = [
    "import axios from \"axios\";",
    "",
    "/**",
    " * " + clientName,
    " * Generated by the SwiftyAPI JavaScript Axios example plugin.",
    " */",
    "export class " + clientName + " {",
    "  constructor(options = {}) {",
    "    this.http = options.http || axios.create({",
    "      baseURL: options.baseURL || " + JSON.stringify(firstServerURL(summary)) + ",",
    "      headers: { \"Accept\": \"application/json\" }",
    "    });",
    "  }"
  ];

  operations.forEach(function(operation) {
    lines.push("");
    lines = lines.concat(renderClientMethod(operation));
  });

  lines.push("}");
  lines.push("");
  return lines.join("\n");
}

function renderClientMethod(operation) {
  var functionName = camelCase(operation.operationID || operation.summary || operation.id);
  var requestBody = operation.requestBody;
  var args = requestBody ? "body, config = {}" : "config = {}";
  var method = operation.method;
  var path = operation.path;
  var hasBody = method === "post" || method === "put" || method === "patch";

  var lines = [
    "  /**",
    "   * " + (operation.summary || operation.id),
    "   * " + method.toUpperCase() + " " + path,
    "   */",
    "  async " + functionName + "(" + args + ") {"
  ];

  if (hasBody) {
    lines.push("    const response = await this.http." + method + "(" + JSON.stringify(path) + ", body, config);");
  } else {
    lines.push("    const response = await this.http." + method + "(" + JSON.stringify(path) + ", config);");
  }

  lines.push("    return response.data;");
  lines.push("  }");
  return lines;
}

function renderModelsFile(operations) {
  var seen = {};
  var lines = [
    "/**",
    " * Lightweight model factories generated by the example plugin.",
    " * They are not validators; they simply document the expected shape and",
    " * provide convenient defaults for tests and examples.",
    " */",
    ""
  ];

  operations.forEach(function(operation) {
    if (operation.requestBody) {
      appendFactory(lines, seen, requestModelName(operation), operation.requestBody.schemaFields || []);
    }

    (operation.responses || []).forEach(function(response) {
      if (response.schemaName || (response.schemaFields || []).length > 0) {
        appendFactory(lines, seen, responseModelName(operation, response), response.schemaFields || []);
      }
    });
  });

  if (lines.length === 6) {
    lines.push("export const models = {};");
  }

  return lines.join("\n");
}

function appendFactory(lines, seen, name, fields) {
  if (seen[name]) {
    return;
  }
  seen[name] = true;

  lines.push("export function create" + pascalCase(name) + "(overrides = {}) {");
  lines.push("  return {");
  fields.forEach(function(field) {
    lines.push("    " + JSON.stringify(field.name) + ": " + exampleValue(field.type) + ",");
  });
  lines.push("    ...overrides");
  lines.push("  };");
  lines.push("}");
  lines.push("");
}

function renderReadme(summary, operations) {
  return [
    "# " + (summary.title || "Generated API"),
    "",
    "Generated by the SwiftyAPI JavaScript Axios example plugin.",
    "",
    "## Operations",
    "",
    operations.map(function(operation) {
      return "- `" + operation.method.toUpperCase() + " " + operation.path + "` - " + (operation.summary || operation.id);
    }).join("\n")
  ].join("\n");
}

function primaryResponse(operation) {
  var responses = operation.responses || [];
  for (var index = 0; index < responses.length; index += 1) {
    if (String(responses[index].statusCode).charAt(0) === "2") {
      return responses[index];
    }
  }
  return responses[0] || null;
}

function requestModelName(operation) {
  if (operation.requestBody && operation.requestBody.schemaName) {
    return operation.requestBody.schemaName;
  }
  return pascalCase(operation.operationID || operation.id) + "Request";
}

function responseModelName(operation, response) {
  if (response && response.schemaName) {
    return response.schemaName;
  }
  return pascalCase(operation.operationID || operation.id) + "Response";
}

function firstServerURL(summary) {
  var servers = summary.servers || [];
  return servers.length > 0 ? servers[0] : "/";
}

function exampleObject(fields) {
  var parts = (fields || []).map(function(field) {
    return JSON.stringify(field.name) + ": " + exampleValue(field.type);
  });
  return "{ " + parts.join(", ") + " }";
}

function exampleValue(type) {
  var normalized = String(type || "string").toLowerCase();
  if (normalized.indexOf("integer") >= 0 || normalized.indexOf("number") >= 0) {
    return "0";
  }
  if (normalized.indexOf("boolean") >= 0) {
    return "false";
  }
  if (normalized.indexOf("array") >= 0) {
    return "[]";
  }
  if (normalized.indexOf("object") >= 0) {
    return "{}";
  }
  return "\"\"";
}

function pascalCase(value) {
  return words(value).map(function(word) {
    if (word === "api") {
      return "API";
    }
    return word.charAt(0).toUpperCase() + word.slice(1);
  }).join("") || "Generated";
}

function camelCase(value) {
  var name = pascalCase(value);
  return name.charAt(0).toLowerCase() + name.slice(1);
}

function words(value) {
  return String(value || "")
    .replace(/([a-z0-9])([A-Z])/g, "$1 $2")
    .split(/[^A-Za-z0-9]+/)
    .filter(Boolean)
    .map(function(word) {
      return word.toLowerCase();
    });
}
